'use client';

import { useEffect, useState } from 'react';
import { Pause, Play, RotateCcw } from 'lucide-react';

const symbols = ['Customer order', 'Information flow', 'Process step', 'Operator', 'Inventory', 'Queue / wait', 'Transport', 'Check / decision', 'Defect / rework', 'Supplier / resources', 'Crepe delivered'];

export default function LeanCrepeLab() {
  const [seconds, setSeconds] = useState(420);
  const [running, setRunning] = useState(false);
  const [iteration, setIteration] = useState(1);
  const [map, setMap] = useState<string[]>(['Customer order', 'Crepe delivered']);
  const [keep, setKeep] = useState(''); const [drop, setDrop] = useState(''); const [start, setStart] = useState('');
  const active = running && seconds > 0;
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => setSeconds(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [active]);
  const toggle = () => { if (!seconds) setSeconds(420); setRunning(value => !value || seconds === 0); };
  const reset = () => { setSeconds(420); setRunning(false); };
  const move = (index: number, offset: number) => setMap(items => { const target = index + offset; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const count = new Set(map).size;
  const clock = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;

  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
    <header className="border-b border-slate-200 pb-7"><p className="text-sm font-semibold text-violet-700">LAN70 Lean Thinking · Interactive group activity</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Crepe Truck Flow Lab</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">In groups of five or more, map the two-operator crepe truck from the customer order back to the resources. Make the flow, handoffs, waiting, and rework visible.</p></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="space-y-5">
      <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-violet-700">Seven-minute sprint · Iteration {iteration}</p><p className="my-3 font-mono text-6xl font-semibold tracking-tight text-slate-950">{clock}</p><div className="grid grid-cols-2 gap-2"><button onClick={toggle} className="flex items-center justify-center gap-2 rounded-md bg-violet-700 px-3 py-3 text-sm font-semibold text-white hover:bg-violet-800">{active ? <Pause size={16} /> : <Play size={16} />}{active ? 'Pause' : 'Start'}</button><button aria-label="Reset timer" onClick={reset} className="rounded-md border border-slate-300 px-3 py-3 text-slate-700 hover:bg-slate-50"><RotateCcw className="mx-auto" size={17} /></button></div></section>
      <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Team roles</h2><p className="mt-3 text-sm leading-7 text-slate-600">Customer / Product Champion<br />Mapper<br />Waste spotter<br />Timekeeper<br />Presenter</p></section>
      <section className="rounded-lg border border-violet-100 bg-violet-50 p-5"><h2 className="font-semibold text-violet-950">Facilitator loop</h2><ol className="mt-3 space-y-2 text-sm leading-6 text-violet-900"><li>1. Start the timebox.</li><li>2. Collect the increment.</li><li>3. Review as the customer.</li><li>4. Retro, then repeat 3–4 times.</li></ol></section>
    </aside><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-5"><div><p className="text-sm font-semibold text-violet-700">Build the map</p><h2 className="mt-1 text-2xl font-semibold">Customer order ← resources</h2></div><div className={`rounded-md border px-4 py-2 text-center ${count === 11 ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-slate-50 text-slate-800'}`}><b>{count}/11 symbols</b><p className="text-xs">{count === 11 ? 'Ready for review' : 'Use every symbol once'}</p></div></div>
      <div className="mt-6 grid gap-6 md:grid-cols-[220px_1fr]"><div><p className="mb-3 text-sm font-semibold text-slate-700">Symbol drawer</p><div className="space-y-2">{symbols.map(symbol => <button key={symbol} onClick={() => setMap(items => [...items, symbol])} className="w-full rounded-md border border-slate-200 bg-white p-2.5 text-left text-sm font-medium text-slate-800 hover:border-violet-300 hover:bg-violet-50">+ {symbol}</button>)}</div></div><div className="min-h-[430px] rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-700">Your process flow</p><div className="mt-4 space-y-2">{map.map((item, index) => <div key={`${item}-${index}`} className="flex items-center gap-3 rounded-md border border-slate-200 bg-white p-3"><span className="text-xs font-semibold text-violet-700">{String(index + 1).padStart(2, '0')}</span><b className="flex-1 text-sm">{item}</b><button disabled={!index} onClick={() => move(index, -1)} className="rounded border border-slate-200 px-2 py-1 text-sm disabled:opacity-30">←</button><button disabled={index === map.length - 1} onClick={() => move(index, 1)} className="rounded border border-slate-200 px-2 py-1 text-sm disabled:opacity-30">→</button></div>)}</div></div></div>
      <div className="mt-6 grid gap-5 md:grid-cols-2"><section className="rounded-lg bg-slate-900 p-5 text-white"><p className="text-sm font-semibold text-violet-300">Product Champion review</p><p className="mt-2 text-sm leading-6 text-slate-300">Is the customer order clear? Are all 11 symbols used? Can every caption be read? Where is the bottleneck, wait, or defect?</p><div className="mt-4 flex gap-2">{[1, 2, 3].map(number => <button key={number} onClick={() => setIteration(number)} className={`rounded-md border px-3 py-1.5 text-sm font-semibold ${iteration === number ? 'border-violet-400 bg-violet-600' : 'border-slate-600'}`}>Iteration {number}</button>)}</div></section><section className="rounded-lg border border-violet-200 bg-violet-50 p-5"><p className="text-sm font-semibold text-violet-950">Two-minute retrospective</p><div className="mt-3 space-y-2"><input value={keep} onChange={event => setKeep(event.target.value)} placeholder="KEEP — what worked?" className="w-full rounded-md border border-violet-200 bg-white p-2.5 text-sm" /><input value={drop} onChange={event => setDrop(event.target.value)} placeholder="DROP — what to stop?" className="w-full rounded-md border border-violet-200 bg-white p-2.5 text-sm" /><input value={start} onChange={event => setStart(event.target.value)} placeholder="PICK UP — next experiment" className="w-full rounded-md border border-violet-200 bg-white p-2.5 text-sm" /></div></section></div>
    </section></div><footer className="mt-8 border-t border-slate-200 pt-5 text-sm text-slate-600">Learning points: timeboxing · clarification · scope · shared ownership · continuous improvement · Definition of Done.</footer>
  </div></main>;
}
