import Link from 'next/link';
import { GlobalCourseStatusForm } from '@/components/tenant-portal/global-course-status-form';
import { PageHeader, TenantShell } from '@/components/tenant-portal/tenant-shell';
import { Button } from '@/components/ui/button';
import { getCoursePortalDataset } from '@/lib/server/course-portal-data';
import { requirePlatformPageSession } from '@/lib/server/tenant-page-auth';

export const dynamic = 'force-dynamic';

export default async function AdminCoursesPage() {
  const session = await requirePlatformPageSession();
  const dataset = await getCoursePortalDataset();

  return (
    <TenantShell user={session.user} admin>
      <PageHeader
        label="Global courses"
        title="OpenMAIC-generated courses"
        description="Courses generated by OpenMAIC can be assigned to one or more organizations."
        action={
          <Button asChild className="bg-violet-700 text-white hover:bg-violet-800">
            <Link href="/course-studio">Open Course Studio</Link>
          </Button>
        }
      />
      <div className="grid gap-4 p-5 sm:p-8 lg:grid-cols-2">
        {dataset.courses.map((course) => {
          const assignedOrganizations = dataset.assignments.filter(
            (assignment) => assignment.courseId === course.id,
          );
          return (
            <article
              key={course.id}
              className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"
            >
              <p className="text-sm font-semibold text-violet-700">{course.category}</p>
              <h2 className="mt-2 text-xl font-semibold tracking-normal">{course.title}</h2>
              <p className="mt-2 text-sm leading-6 text-slate-600">{course.description}</p>
              <p className="mt-4 text-sm text-slate-500">
                Assigned to {assignedOrganizations.length} organization
                {assignedOrganizations.length === 1 ? '' : 's'}
              </p>
              <p className="mt-2 text-xs text-slate-500">
                Current status:{' '}
                <span className="font-semibold capitalize text-slate-700">{course.status}</span>
              </p>
              <GlobalCourseStatusForm course={course} />
            </article>
          );
        })}
      </div>
    </TenantShell>
  );
}
